apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
  labels:
    app: cpu-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: cpu-stress
        image: busybox:1.36
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        command: ["/bin/sh"]
        args:
        - "-c"
        - "while true; do for i in $(seq 1 10000); do echo $i | md5sum; done; sleep 1; done"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-stress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-stress
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-stress
spec:
  selector:
    app: cpu-stress
  ports:
  - port: 80
    targetPort: 80
